[package]
name = "tarkov-tactical-board-tauri"
version = "1.5.7"
description = "Tarkov Tactical Board desktop shell powered by Tauri"
authors = ["luopc1218"]
edition = "2021"

[lib]
name = "tarkov_tactical_board_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
