services:
  tarkov_frontend:
    container_name: tarkov_frontend
    image: ${FRONTEND_IMAGE:-luopc1218docker/tarkov-tactical-board-frontend:edge}
    restart: unless-stopped
    ports:
      - '0.0.0.0:10001:80'
